version: 2

project_name: ak-asset-check

builds:
  - env:
      - CGO_ENABLED=0
    main: .
    ldflags:
      - -s -w -X main.buildDate={{ .Date }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - none*


checksum:
  name_template: "checksums.txt"

release:
  draft: false
  prerelease: auto
